### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by ceiri** [mjwells2002/minecraft-lwjgl-macos#1]
This workaround appears not to work in 1.18.2 - as Mojang continues to ignore how easy of an implementation native rendering would be on ARM Macs.

**Comment by mjwells2002** [comment]
Any error? This should work perfectly on 1.18.2

**Comment by mjwells2002** [comment]
I don't have a arm Mac to test with right now

**Comment by ceiri** [comment]
I'm such an idiot, I didn't update the Intermediary Mappings. I have to repeat how thankful I am for this, simple things like lag between world switching and overall FPS has improved significantly and of course the sound output fix has been useful!

**Comment by mjwells2002** [comment]
Haha been there done that
